### ISSUE TITLE
Small tweak to get this running on linux

### ISSUE THREAD

**Issue by shinzlet** [cconklin/crOpenCL#1]
It seems that removing the key `framework:` in the `Link` annotation in `src/crOpenCL/libOpenCL.cr` gets this to correctly compile and run on linux (at least on my machine).

I don't have a mac, so I can't test if that also works on macOS. [I have a fork](https://github.com/shinzlet/crOpenCL) of this repo that I'm using for a hobby project, and all I've done is make the change described above. If this change breaks functionality on macs, I'm sure a macro could patch things up for both systems.

Also, while I'm at it, @cconklin, thank you so much for writing this library! I'm pretty excited about it.

**Comment by cconklin** [comment]
See if 7ff072b3d04b2f8c744567e3839c133e809e55d8 works for you. If it does, let me know and I'll close this issue.

> Also, while I'm at it, @cconklin, thank you so much for writing this library! I'm pretty excited about it.

Thanks! That said, be careful when using it; I don't think it's all that stable. Based on some uncommitted changes that I found in my local clone, it looks like it's possible for the GC to reclaim kernel arguments before the kernel is executed. This also doesn't behave well at all in the presence of union types since the size of the union is (at minimum) the size of the largest member type.

**Comment by shinzlet** [comment]
@cconklin Works great! Thanks a ton. And I'm just using it for a little hobby project, which I don't need anything too stable for. I appreciate the warning, though.
